name: Publish

on:
  workflow_run:
    workflows: ["Build precompiled NIFs"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      HEX_API_KEY: ${{ secrets.HEXPM_API_KEY }}
      RUST_TOOLCHAIN_VERSION: nightly-2023-02-14
      VEGA_LITE_CONVERT_BUILD: true

    steps:
      - uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "${{ env.RUST_TOOLCHAIN_VERSION }}"

      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.x
          elixir-version: 1.14.x

      - run: make prepare
      - run: mix compile --docs
      - run: mix rustler_precompiled.download VegaLiteConvert --all --print
      - run: mix hex.publish --yes
